### ISSUE TITLE
notifyUrl sensitive informations

### ISSUE THREAD

**Issue by ludook** [kubereboot/charts#111]
Hello,

`configuration.notifyUrl` chart parameter can contains some sensitive informations (slack secret token for example)

So, how to import this information from a kubernetes secret ?
in default values.yaml we can read this :
```
extraEnvVars:
#  - name: slackHookUrl
#    valueFrom:
#      secretKeyRef:
#        name: secret_name
#        key: secret_key
```
but it seems not working with notifyUrl , like this for example : 
```
extraEnvVars:
  - name: notifyUrl 
    valueFrom:
      secretKeyRef:
        name: slack_notify_url
        key: slack://******/*******/*******
```

maybe I missed some documentation or it is not possible to override parameters with envvars ?
if second answer, could you please add this feature ?

thank you for your great job :-)
