### ISSUE TITLE
How to get config activated in an app-in-apps scenario with Chart/values?

### ISSUE THREAD

**Issue by svenakela** [kubereboot/charts#54]
I would like to deploy kured with ArgoCD and we have an app-in-apps setup. Kured is deployed with following `Chart.yaml`:

    apiVersion: v2
    name: kured
    description: A Helm chart for Kured
    type: application
    version: 0.0.1
    appVersion: 5.2.0
    
    dependencies:
    - name: kured
      repository: https://kubereboot.github.io/charts
      version: 5.2.0

This part works fine, ArgoCD picks it up and deploy Kured as expected. I would like to set some configuration points (endTime, startTime etc) and whatever structure I set in the `values.yaml` file the config is not applied. 

We do have other external apps deployed in the same way, like ingress-nginx, where the `values.yaml` file adds/overrides values for the dependency. It would be great to get an example of a working `values.yaml` that sets one or two run parameters correctly.

Thanks in advance.

**Comment by ckotzbauer** [comment]
I never tested such a structure before, but charts like the `kube-prometheus-stack` from the `prometheus-community` are also using dependency-charts and those values are below a key named the same as the dependency-name in chart.yaml.

So instead of
```yaml
configuration:
  metricsHost: ""
```

you may write:
```yaml
kured:
  configuration:
    metricsHost: ""
```

Did you test this?

**Comment by Tokynet** [comment]
I know this is old, putting my working config, just in-case anyone else stumbles on this question.

My configuration is all in 1 repo (casita) I have a folder (called argo-apps) in which I put all my Argo applications (kind) files. Then I have another separate directory called cluster in which I create a directory per application. In this directory is where I place the values.yaml file for any helm application that I install via Argocd.

```shell
casita/
    ├── argo-apps/
    │       └── kured.yaml
    └── cluster/
             └── kured/
                  └── values.yaml
```

Here is the content of the argocd application (kind) I use for kured:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubereboot.github.io/charts
      chart: kured
      targetRevision: 5.6.1
      helm:
        valueFiles:
          - $kuredvalues/cluster/kured/values.yaml
    - repoURL: git@github.com:Tokynet/casita.git
      path: cluster/kured
      ref: kuredvalues

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
```
_I changed the project name back to default, since that should be easier to follow on a vanilla argocd installation._
