### ISSUE TITLE
Mounting of custom volumes fails templating

### ISSUE THREAD

**Issue by yaraskm** [kubereboot/charts#71]
I believe that there is an issue with the indentation level being applied in the generated Yaml when specifying `volumeMounts`. 

**Reproducing**

1. Create a simple `values.yaml` file like so:
```yaml
volumeMounts: []
volumes: []
```

2. Run `helm template`. which should succeed as expected:
```bash
$ helm template -n my-ns kured kubereboot/kured -f values.yaml
---
# Source: kured/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kured
  namespace: my-ns
  labels:
    app.kubernetes.io/name: kured
    helm.sh/chart: kured-5.4.1
    app.kubernetes.io/instance: kured
    app.kubernetes.io/managed-by: Helm
---
# Source: kured/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
...
```

3. Set a custom volume mount. In this case, say that I have a custom CA certificate stored in a Secret object that I want to mount. N.b., this works as expected when I modify an existing Daemonset:
```yaml
volumeMounts:
  - name: cacert
    mountPath: /etc/ssl/cert.pem
    subPath: ca.pem
    readOnly: true

volumes:
  - name: cacert
    secret:
      secretName: cacert
```

4. Try to template the Yaml again:
```bash
$ helm template -n my-ns kured kubereboot/kured -f values.yaml
Error: YAML parse error on kured/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 56: did not find expected key

Use --debug flag to render out invalid YAML
```
Repeating this with `--debug` gives the following `volumeMounts` section:
```yaml
...
          volumeMounts:
          - mountPath: /sentinel
            name: sentinel
            readOnly: true
            - mountPath: /etc/ssl/cert.pem
              name: cacert
              readOnly: true
              subPath: ca.pem
...
```

which should be:
```yaml
...
          volumeMounts:
          - mountPath: /sentinel
            name: sentinel
            readOnly: true
          - mountPath: /etc/ssl/cert.pem
            name: cacert
            readOnly: true
            subPath: ca.pem
...
```

**Fix**
I can submit a PR to fix this, as the indentation level just needs to be changed from 12 to 10 I believe.
