### ISSUE TITLE
rebootSentinelCommand is not respected

### ISSUE THREAD

**Issue by shanduur** [kubereboot/charts#77]
`values.yaml`:

```yaml
    configuration:
      drainGracePeriod: 15
      drainTimeout: "150s"
      forceReboot: true
      rebootSentinelCommand: 'sh -c "! needs-restarting --reboothint"'
```

Output of `kubectl get -o=yaml -n=kube-system daemonsets.apps kured`

```yaml
...
    spec:
      containers:
      - args:
        - --ds-name=kured
        - --ds-namespace=kube-system
        - --metrics-port=8080
        - --force-reboot
        - --drain-grace-period=15
        - --drain-timeout=150s
        - --reboot-sentinel=/sentinel/reboot-required
        - --reboot-command=/bin/systemctl reboot
        - --log-format=text
        - --concurrency=1
 ...
 ```
