### ISSUE TITLE
notifyURL not functional

### ISSUE THREAD

**Issue by fmunteanu** [kubereboot/charts#84]
I created a Kured app in Slack and tested the functionality with the provided Webhook URL:

```shell
curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/<redacted>/<redacted>/<redacted>
```

![image](https://github.com/kubereboot/charts/assets/19806136/7ed34ae5-a69c-4b44-90dc-8d62de8620cc)

Chart settings:

```yaml
USER-SUPPLIED VALUES:
configuration:
  concurrency: 1
  endTime: "07:59"
  notifyUrl: https://hooks.slack.com/services/<redacted>/<redacted>/<redacted>
  period: 15m
  rebootDelay: 60s
  startTime: "04:00"
  timeZone: UTC
metrics:
  create: true
  labels:
    release: kube-prometheus-stack
  namespace: kube-system
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi
service:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: 8080
    prometheus.io/scrape: true
  create: true
  name: kured
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/control-plane
  operator: Exists
```

I also need some clarifications if the `messageTemplate` chart settings are related to Slack only.

I was wondering if anyone can shed some light where the issue resides. cc @dholbach @jackfrancis.
